#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use StremioSaver\Commands\SaveSubtitlesCommand;
use StremioSaver\Commands\SaveMovieCommand;
use StremioSaver\Commands\CleanCacheCommand;

$application = new Application();
$application->add(new SaveSubtitlesCommand());
$application->add(new SaveMovieCommand());
$application->add(new CleanCacheCommand());
$application->run();